name: Build

on:
  push:
    # branches: [master]
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # include:
        #   - os: macos-latest
        #     NAME: macos

        #   - os: ubuntu-latest
        #     NAME: linux

        #   - os: windows-latest
        #     NAME: windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Cleanup Artifacts for windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     npx rimraf "release/\!(*.exe\|latest.yml)"

      # - name: Cleanup Artifacts for macos
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     npx rimraf "release/!(*.dmg|latest-mac.yml)"

      # - name: Cleanup Artifacts for linux
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     npx rimraf "release/!(*.AppImage|latest-linux.yml)"

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: release_on_${{ matrix.os }}
      #     path: release/
          # retention-days: 5
      
      - name: Release for windows
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release for macos
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.dmg
            release/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release for linux
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.AppImage
            release/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}